### ISSUE TITLE
[IMPROVEMENT] Move publishing via pom.xml

### ISSUE THREAD

**Issue by romankh3** [romankh3/image-comparison#154]
** Describe your idea of the improvement **
Due to the reason, that GitHub supports pom.xml, but doesn't build.gradle, `image-comparison` must be moved to Maven and pom.xml

**Comment by Hexronimo** [comment]
+1 for this one. Your Gradle projects don't even work on my machine without spending some time on StackOverflow trying to remember why this error happen (без танцев с бубном в общем).

**Comment by romankh3** [comment]
I spent a few days to research of how to publish to Maven Central and jCenter via bintray and didn't found the full solution. that's why it was moved to backlog and I don't know where I would do it.

Please, describe your problem with Gradle. I merged a new Gradle version, maybe it relates to your problem.

**Comment by Hexronimo** [comment]
Yes, I believe it's related to Gradle version, I will check it in the evening. I'm not very familiar with the Gradle, because I use only Maven in my projects, so I'm not even sure that error is on your side, maybe it's in my workspace configuration. At least from what I see now, IntelliJ says "Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.". But I still can run it. 
Also, please fix two typos in your Example class in README.md (method name and ";a")

**Comment by romankh3** [comment]
Can you fix typos? As I can see, you've been forked `image-comparison`)

**Comment by Hexronimo** [comment]
Ok, I'll do everything at the evening or if I'll have free time at work.

**Comment by romankh3** [comment]
thanks!

**Comment by Hexronimo** [comment]
I'm trying to run and check it quickly, but got RuntimeException:
`Exception in thread "main" java.lang.IllegalArgumentException: -8
	at java.base/java.util.stream.ReferencePipeline.skip(ReferencePipeline.java:476)
	at com.github.romankh3.image.comparison.ImageComparison.drawRectanglesOfDifferences(ImageComparison.java:358) (...)`
so it's somewhere on ".skip" in:
`rectanglesForDraw = rectangles.stream()
                    .sorted(Comparator.comparing(Rectangle::size))
                    .skip(rectangles.size() - maximalRectangleCount)
                    .collect(Collectors.toList());`
Maybe I'm doing something wrong?  
I created main method in ImageComparion and added code from your Example class and rewrote the creation of InputStream at ImageComparisonUtil.readImageFromResources() because have no idea where to put images when using getResourceAsStream(path) (and it found images after this rewriting). I still don't think it may affect rectangles somehow. 
The good thing is that if I have RuntimeError it seems like Gradle is ok.

**Comment by romankh3** [comment]
Finally, I've got what are you talking about! This `Example` from README is shown how to use, not for running it... I'll update it to make it runnable.

Thanks for your catch. Also, you can create a Bug issue to track it.

Best regards,
Roman.

**Comment by Hexronimo** [comment]
Well, I understand that you want to show public methods and constructors in this Example.class (and I said that it's from readme in the comment above), but it actually can be used to copy-paste code and quickly see the result of this program work (I just commented unwanted constructors and renamed result.png to an actual path).
